export { default as Home } from "./Home"
export { default as Games } from "./Games"
export { default as Ladder } from "./Ladder"
export { default as Boards } from "./Boards"
export { default as Profile } from "./Profile"
export { default as Login } from "./Login"
export { default as Bets } from "./Bets"